import { Component, computed, DestroyRef, inject, signal } from '@angular/core';
import { applyEach, form, FormField, required, validate } from '@angular/forms/signals';
import { FloatLabel } from "primeng/floatlabel";
import { FormsModule } from '@angular/forms';
import { InputTextModule } from 'primeng/inputtext';
import { DatePickerModule } from 'primeng/datepicker';
import { SelectModule } from 'primeng/select';
import { AutoCompleteModule } from 'primeng/autocomplete';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router } from '@angular/router';
import { FieldErrorSComponent } from '../../../../shared/field-error-s/field-error-s.component';
import { AutoDropdown } from '../../../../Models/Pagination.model';
import { DataLayerService } from '../../../../services/data-layer.service';
import { BaseApiService } from '../../../../services/base-api.service';
import { enumToOptions } from '../../../../shared/Utility';
import { AttributeDefinitionDropdown, ProductAttributeValueDto, ProductDTO, ProductFormLookups, ProductType, ProductVariantDto, UOM, WareHouseStockDto } from '../../../../Models/Inventory/Product.model';
import { FormDataService } from '../../../../services/formData.service';
@Component({
  selector: 'app-add-product',
  imports: [FloatLabel, FieldErrorSComponent, FormsModule, InputTextModule, DatePickerModule, SelectModule, FormField, AutoCompleteModule],
  templateUrl: './add-product.component.html',
  styleUrl: './add-product.component.css'
})
export class AddProductComponent {

  //Initial Calls 
  wareHouses = signal<AutoDropdown[]>([]);
  productCategories = signal<AutoDropdown[]>([]);
  brands = signal<AutoDropdown[]>([]);
  attributeDefinitions = signal<AttributeDefinitionDropdown[]>([]);

  //properties
  private dataService = inject(DataLayerService);
  private destroyRef = inject(DestroyRef);
  private base = inject(BaseApiService);
  private activatedRoute = inject(ActivatedRoute);
  private router = inject(Router);
  private formservice = inject(FormDataService);


  submit = signal<boolean>(false);
  formSubmitted = signal<boolean>(false);
  backendErrors = signal<Record<string, string[]>>({});
  errors = signal<string[]>([]);
  uomList = signal(enumToOptions(UOM, true));
  productTypes = signal(enumToOptions(ProductType, true));
  isEditMode = signal<boolean>(false);
  existingVariantIds = signal<string[]>([]);
  existingStockWarehouseIds = signal<Record<number, number[]>>({});
  variantImagePreviews = signal<Record<number, string>>({});
  warehouseLocations = signal<Record<number, AutoDropdown[]>>({});
  autoGeneratedSku = signal<Record<number, string>>({});


  //Load Voucher for Edit Mode
  ngOnInit() {
    this.loadFormLookups();
    this.activatedRoute.paramMap.pipe(
      takeUntilDestroyed(this.destroyRef)).subscribe(param => {
        const id = param.get('id');
        if (id) {

          this.isEditMode.set(true);
          this.loadProduct(id);
        }
      });
  }


  // Initial template for Attribute Values
  private readonly defaultAttributeValue: ProductAttributeValueDto = {
    attributeDefinitionId: null,
    attributeName: '',
    attributeValueId: null,
    value: ''
  };

  // Initial template for Warehouse Stock
  private readonly defaultWarehouseStock: WareHouseStockDto = {
    warehouseId: null,
    warehouseLocationId: null,
    warehouseName: '',
    warehouseLocationName: '',
    quantity: 0,
    unitCost: 0
  };

  // Initial template for a Variant
  private readonly defaultVariant: ProductVariantDto = {
    sku: '',
    barcode: '',
    description: '',
    costPrice: 0,
    sellingPrice: 0,
    netWeight: 0,
    grossWeight: 0,
    length: 0,
    width: 0,
    height: 0,
    imageUrl: null,
    image: undefined,
    isActive: true,
    removedImage: false,
    attributeValues: [{ ...this.defaultAttributeValue }],
    initialStock: []
  };

  // Main Product Root Model Template
  private readonly defaultProduct: ProductDTO = {
    productName: '',
    productNumber: '',
    productDescription: '',
    uom: null,
    productType: null,
    taxRate: 0,
    isActive: true,
    productCategoryId: null,
    brandId: null,
    variants: [{ ...this.defaultVariant }]
  };

  // Initialize Main Signal
  productModel = signal<ProductDTO>(this.defaultProduct);

  // Validations
  productForm = form(this.productModel, (schema) => {
    // Root Product Validations
    required(schema.productName, { message: 'Product Name is required', });
    required(schema.productNumber, { message: 'Product Number is required' });
    required(schema.uom, { message: 'UOM is required' });
    required(schema.productType, { message: 'Product Type is required' });
    required(schema.productCategoryId, { message: 'Category is required' });

    // Level 1: Variants Collection Validation
    applyEach(schema.variants, (variant) => {
      required(variant.sku, { message: 'SKU is required', });

      // min(path, 0) allows exactly 0 through — doesn't match "must be > 0".
      // Use a strict validate() instead of min() for a true greater-than-zero rule.
      validate(variant.costPrice, ({ value }) => {
        const price = value();
        if (price == null || price <= 0) {
          return { kind: 'positiveCostPrice', message: 'Cost price must be greater than 0' };
        }
        return null;
      });

      validate(variant.sellingPrice, ({ value }) => {
        const price = value();
        if (price == null || price <= 0) {
          return { kind: 'positiveSellingPrice', message: 'Selling price must be greater than 0' };
        }
        return null;
      });

      // Level 2: Initial Stock inside Variant
      // Same warehouse + location cannot be selected more than once
      applyEach(variant.initialStock, (stock) => {
        required(stock.warehouseId, { message: 'Warehouse is required', });
        validate(stock.quantity, ({ value }) => {
          const qty = value();
          if (qty == null || qty <= 0) {
            return { kind: 'positiveQuantity', message: 'Quantity must be greater than 0' };
          }
          return null;
        });

        validate(stock.unitCost, ({ value }) => {
          const cost = value();
          if (cost == null || cost <= 0) {
            return { kind: 'positiveUnitCost', message: 'Unit cost must be greater than 0' };
          }
          return null;
        });

        validate(stock.warehouseId, ({ value, valueOf }) => {
          const currentWarehouseId = value();

          if (!currentWarehouseId) {
            return null;
          }

          const currentLocationId = valueOf(stock.warehouseLocationId);
          const stockRows = valueOf(variant.initialStock) ?? [];

          // Treat "no location" as its own comparable bucket (empty string)
          // so a warehouse-with-no-location matches only other
          // warehouse-with-no-location rows, and a warehouse+location
          // pair matches only the same pair.
          const currentKey = `${currentWarehouseId}|${currentLocationId ?? ''}`;

          const duplicateCount = stockRows.filter(
            (s) => `${s.warehouseId}|${s.warehouseLocationId ?? ''}` === currentKey
          ).length;

          if (duplicateCount > 1) {
            return {
              kind: 'duplicateWarehouseLocation',
              message: 'This combination is already added to this variant',
            };
          }

          return null;
        });
      });

    });
  });
  //Method to Update Fields For Non supporting Primeng Fields
  updateField<K extends keyof ProductDTO>(field: K, value: ProductDTO[K]) {
    this.productModel.update(prev => ({
      ...prev,
      [field]: value
    }));
  }
  // ✅ Update a specific field inside a specific line by index
  updateLineField<K extends keyof ProductVariantDto>(
    index: number,
    field: K,
    value: ProductVariantDto[K]
  ) {
    this.productModel.update(prev => {
      const variants = [...prev.variants];           // shallow copy the array
      variants[index] = { ...variants[index], [field]: value }; // copy the line, update field
      return { ...prev, variants };
    });
  }
  // Update field inside an attribute row of a variant
  updateVariantAttributeField<K extends keyof ProductAttributeValueDto>(
    variantIndex: number, attrIndex: number,
    field: K, value: ProductAttributeValueDto[K]
  ) {
    this.productModel.update(prev => {
      const variants = [...prev.variants];
      const attributeValues = [...variants[variantIndex].attributeValues];

      attributeValues[attrIndex] = {
        ...attributeValues[attrIndex],
        [field]: value
      };

      variants[variantIndex] = { ...variants[variantIndex], attributeValues };
      return { ...prev, variants };
    });
    this.maybeAutoGenerateSku(variantIndex);
  }

  // Update field inside a stock row of a variant
  updateVariantStockField<K extends keyof WareHouseStockDto>(
    variantIndex: number,
    stockIndex: number,
    field: K,
    value: WareHouseStockDto[K]
  ) {
    this.productModel.update(prev => {
      const variants = [...prev.variants];
      const initialStock = [...variants[variantIndex].initialStock];

      initialStock[stockIndex] = {
        ...initialStock[stockIndex],
        [field]: value
      };

      variants[variantIndex] = { ...variants[variantIndex], initialStock };
      return { ...prev, variants };
    });
  }
  // --- VARIANT LEVEL ---
  addVariant(): void {
    const defaults = this.generateSmartVariant(this.productModel().variants);

    const newVariant: ProductVariantDto = {
      ...this.defaultVariant,
      ...defaults,
      // fresh arrays — never reuse defaultVariant's array references across variants
      attributeValues: [{ ...this.defaultAttributeValue }],
      initialStock: []
    };

    this.productModel.update(prev => ({
      ...prev,
      variants: [...prev.variants, newVariant]
    }));
  }

  deleteVariant(variantIndex: number): void {
    const targetVariant = this.productModel().variants[variantIndex];

    // Block deletion if variant exists in the database
    if (this.isEditMode() && targetVariant.id && this.existingVariantIds().includes(targetVariant.id)) {
      this.errors.set(['Persisted variants cannot be deleted directly. Deactivate them instead.']);
      return;
    }

    this.errors.set([]); // Clear previous errors if valid

    this.productModel.update(prev => {
      if (prev.variants.length === 1) {
        return { ...prev, variants: [{ ...this.defaultVariant }] };
      }
      return { ...prev, variants: prev.variants.filter((_, i) => i !== variantIndex) };
    });
  }

  addStockLine(variantIndex: number): void {
    const stockArray = this.productModel().variants[variantIndex].initialStock;

    // No existing stock lines -> add the first one
    if (stockArray.length === 0) {
      this.productModel.update(prev => {
        const variants = [...prev.variants];
        variants[variantIndex] = { ...variants[variantIndex], initialStock: [{ ...this.defaultWarehouseStock }] };
        return { ...prev, variants };
      });

      return;
    }

    // Validate the last existing stock line before adding another
    const lastIndex = stockArray.length - 1;
    const currentStockRow = this.productForm.variants[variantIndex].initialStock[lastIndex];

    const isInvalid = currentStockRow.warehouseId().invalid() || currentStockRow.quantity().invalid() || currentStockRow.unitCost().invalid();

    if (isInvalid) {
      currentStockRow.warehouseId().markAsTouched();
      currentStockRow.quantity().markAsTouched();
      currentStockRow.unitCost().markAsTouched();

      return;
    }

    // Last row is valid -> add a new empty stock line
    this.productModel.update(prev => {
      const variants = [...prev.variants];
      variants[variantIndex] = { ...variants[variantIndex], initialStock: [...variants[variantIndex].initialStock, { ...this.defaultWarehouseStock }] };
      return { ...prev, variants };
    });
  }

  deleteStockLine(variantIndex: number, stockIndex: number): void {
    const targetVariant = this.productModel().variants[variantIndex];

    // If editing an EXISTING variant, initial stock is historical
    // and should not be modified or deleted.
    if (this.isEditMode() && targetVariant.id && this.existingVariantIds().includes(targetVariant.id)) {
      this.errors.set(['Initial stock for existing variants cannot be modified or deleted.']);
      return;
    }

    this.errors.set([]);

    this.productModel.update(prev => {
      const variants = [...prev.variants];
      variants[variantIndex] = { ...variants[variantIndex], initialStock: variants[variantIndex].initialStock.filter((_, i) => i !== stockIndex) };

      return { ...prev, variants };
    });
  }

  //Create method
  createProduct(event: Event) {
    if (this.submit()) {
      return;
    }
    //Checking Duplicate variant attributes
    console.log(this.duplicateVariantIndices());
    if (this.duplicateVariantIndices().size > 0) {
      this.errors.set(['Two or more variants have the same attribute combination. Each variant must be unique.']);
      return;
    }
    //Validating the Form
    event.preventDefault();
    this.submit.set(true);
    this.formSubmitted.set(true);
    if (this.productForm().invalid()) {
      this.productForm().markAsTouched();
      this.submit.set(false);
      return;
    }

    //Accessing Form Value
    this.errors.set([]);
    this.backendErrors.set({});
    const formvalue = this.productForm().value() as ProductDTO;
    const formdata = this.formservice.buildFormData(formvalue);

    //for update and create
    const url = `Products`;
    const request$ = this.isEditMode()
      ? this.dataService.edit<ProductDTO>(url, formvalue.id?.toString() ?? '', formdata)
      : this.dataService.create<ProductDTO>(url, formdata);

    //Making Api Call
    request$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: () => {
        //Redirect To List For Edit
        if (this.isEditMode()) {
          this.router.navigate(['Inventory', 'productlist']);
          this.base.globalMessage('success', 'Product Updated Successfully', false);
          return;
        }
        this.base.globalMessage('success', 'Product Added Successfully', false);
        //Reset the form
        this.productForm().reset({ ...this.defaultProduct, variants: [{ ...this.defaultVariant }] });
        this.submit.set(false);
        this.formSubmitted.set(false);
      },
      error: (err) => {
        if (err.error.errors) {
          this.backendErrors.set(err.error.errors);
        } else {
          this.base.handleError(err, err.error.message);
        }
        this.submit.set(false);
      }
    });

  }

  loadFormLookups(): void {
    this.dataService.getAll<ProductFormLookups>('Dropdowns/ProductFormLookups')
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (res) => {
          this.wareHouses.set(res.warehouses);
          this.productCategories.set(res.categories);
          this.brands.set(res.brands);
          this.attributeDefinitions.set(res.attributeDefinitions);
        },
        error: (err) => {
          this.base.handleError(err, err.error?.message);
        }
      });
  }

  loadProduct(id: string) {
    this.dataService.getById<ProductDTO>('Products', id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (data) => {
        this.productModel.set(data);
        //Map variant ids
        const vIds = data.variants.map(v => v.id).filter((vId): vId is string => !!vId);
        this.existingVariantIds.set(vIds);
      },
      error: (err) => {
        this.base.handleError(err, err.error?.message);
        this.router.navigate(['Inventory', 'productlist']);
      }
    });
  }
  onWarehouseChange(variantIndex: number, stockIndex: number, warehouseId: number | null): void {
    // Set warehouse
    this.updateVariantStockField(variantIndex, stockIndex, 'warehouseId', warehouseId);

    // Reset previously selected location
    this.updateVariantStockField(variantIndex, stockIndex, 'warehouseLocationId', null);

    if (warehouseId == null) {
      return;
    }

    // Already loaded? Don't call API again
    if (this.warehouseLocations()[warehouseId]) {
      return;
    }

    this.loadWarehouseLocations(warehouseId);
  }

  loadWarehouseLocations(warehouseId: number): void {

    this.dataService.getAllSimple<AutoDropdown>(`Dropdowns/LocationsByWarehouse/${warehouseId}`)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (locations) => {
          this.warehouseLocations.update(current => ({ ...current, [warehouseId]: locations }));
        },
        error: (err) => {
          this.base.handleError(err, err.error?.message);
        }
      });
  }

  getWarehouseLocations(warehouseId: number | null): AutoDropdown[] {
    if (warehouseId == null) {
      return [];
    }

    return this.warehouseLocations()[warehouseId] ?? [];
  }
  onVariantImageSelected(event: Event, variantIndex: number) {

    const preview = signal(this.variantImagePreviews()[variantIndex] ?? '');

    const file = this.formservice.onImageSelected(event, preview);

    if (!file) {
      return;
    }
    // FileReader in FormDataService is async, so don't read preview() here.
    // Create the preview directly from the selected File.
    const previewUrl = URL.createObjectURL(file);

    this.variantImagePreviews.update(prev => ({ ...prev, [variantIndex]: previewUrl }));

    // Store actual File
    this.productModel.update(prev => {
      const variants = [...prev.variants];
      variants[variantIndex] = { ...variants[variantIndex], image: file, removedImage: false };
      return { ...prev, variants };
    });

  }
  removeVariantImage(variantIndex: number) {

    const preview = signal(this.variantImagePreviews()[variantIndex] ?? '');

    this.formservice.removeImage(preview, `variantImage_${variantIndex}`);

    this.variantImagePreviews.update(prev => ({ ...prev, [variantIndex]: '' }));

    this.productModel.update(prev => {
      const variants = [...prev.variants];
      variants[variantIndex] = { ...variants[variantIndex], image: undefined, removedImage: this.isEditMode() ? true : false };
      return { ...prev, variants };
    });
  }

  // Prevent Duplication of Attributes
  duplicateVariantIndices = computed<Set<number>>(() => {
    const variants = this.productModel().variants ?? [];
    const definitions = this.attributeDefinitions() ?? [];
    const seen = new Map<string, number[]>();

    variants.forEach((variant, variantIdx) => {
      const rawAttrs = variant.attributeValues ?? [];
      if (rawAttrs.length === 0) return;

      // Map each attribute value option, resolving the parent definition ID from attributeDefinitions()
      const validAttrs = rawAttrs
        .map((attr, attrIdx) => {
          // Fallback to definition ID from definitions signal if not present on the model item
          const defId = attr.attributeDefinitionId ?? definitions[attrIdx]?.id;
          const valId = attr.attributeValueId;
          return { defId, valId };
        })
        .filter((a) => a.defId != null && a.valId != null);

      // Skip incomplete variants (user hasn't selected options across all dynamic dropdowns yet)
      if (validAttrs.length === 0 || validAttrs.length !== definitions.length) {
        return;
      }

      // Sort to ensure combination order doesn't matter (e.g. Color:Red|Size:XL == Size:XL|Color:Red)
      const key = validAttrs
        .map((a) => `${a.defId}:${a.valId}`)
        .sort()
        .join('|');

      const existing = seen.get(key) ?? [];
      seen.set(key, [...existing, variantIdx]);
    });

    const duplicates = new Set<number>();
    for (const indices of seen.values()) {
      if (indices.length > 1) {
        indices.forEach((idx) => duplicates.add(idx));
      }
    }

    return duplicates;
  });

  // Builds a SKU like "PRD-RED-XL" from product number + selected attribute codes
  private buildSkuFromAttributes(variantIndex: number): string {
    const product = this.productModel();
    const variant = product.variants[variantIndex];
    const definitions = this.attributeDefinitions();

    const productPart = (product.productNumber || 'PRD')
      .toUpperCase()
      .trim()
      .replace(/\s+/g, '-');

    const attrCodes = (variant.attributeValues ?? [])
      .map((attr, attrIdx) => {
        const def = definitions[attrIdx];
        const option = def?.values.find(v => v.id === attr.attributeValueId);
        return option?.code?.toUpperCase();
      })
      .filter((code): code is string => !!code);

    return [productPart, ...attrCodes].join('-');
  }


  // Actually generates + writes the sku
  generateSku(variantIndex: number): void {
    const newSku = this.buildSkuFromAttributes(variantIndex);
    this.autoGeneratedSku.update(prev => ({ ...prev, [variantIndex]: newSku }));
    this.updateLineField(variantIndex, 'sku', newSku);
  }

  // Called after any attribute pick — only overwrites if user hasn't customized it
  private maybeAutoGenerateSku(variantIndex: number): void {
    // Don't touch SKUs of already-persisted variants in edit mode
    const variant = this.productModel().variants[variantIndex];
    if (this.isEditMode() && variant.id && this.existingVariantIds().includes(variant.id)) {
      return;
    }

    const lastAuto = this.autoGeneratedSku()[variantIndex];
    const currentSku = variant.sku;

    if (!currentSku || currentSku === lastAuto) {
      this.generateSku(variantIndex);
    }
  }
  // Analogous to generateSmartLines — pulls forward shared fields from the last variant
  private generateSmartVariant(variants: ProductVariantDto[]): Partial<ProductVariantDto> {
    if (!variants.length) return {};

    const lastVariant = variants[variants.length - 1];

    return {
      costPrice: lastVariant.costPrice,
      sellingPrice: lastVariant.sellingPrice,
      netWeight: lastVariant.netWeight,
      grossWeight: lastVariant.grossWeight,
      length: lastVariant.length,
      width: lastVariant.width,
      height: lastVariant.height,
    };
  }


}
