import { Component, computed, DestroyRef, inject, OnInit, signal } from '@angular/core';
import { applyEach, form, FormField, required, validate } from '@angular/forms/signals';
import { FloatLabel } from "primeng/floatlabel";
import { FormsModule } from '@angular/forms';
import { InputTextModule } from 'primeng/inputtext';
import { DatePickerModule } from 'primeng/datepicker';
import { SelectModule } from 'primeng/select';
import { AutoCompleteModule } from 'primeng/autocomplete';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router } from '@angular/router';
import { FieldErrorSComponent } from '../../../../shared/field-error-s/field-error-s.component';
import { AutoDropdown } from '../../../../Models/Pagination.model';
import { BaseApiService } from '../../../../services/base-api.service';
import { enumToOptions } from '../../../../shared/Utility';
import { AttributeDefinitionDropdown, ProductAttributeValueDto, ProductDTO, ProductType, ProductVariantDto, UOM, WareHouseStockDto } from '../../../../Models/Inventory/Product.model';
import { FormDataService } from '../../../../services/formData.service';
import { ProductService } from '../../../../services/Inventory/product.service';

@Component({
  selector: 'app-add-product',
  imports: [FloatLabel, FieldErrorSComponent, FormsModule, InputTextModule, DatePickerModule, SelectModule, FormField, AutoCompleteModule],
  templateUrl: './add-product.component.html',
  styleUrl: './add-product.component.css'
})
export class AddProductComponent implements OnInit {

  wareHouses = signal<AutoDropdown[]>([]);
  productCategories = signal<AutoDropdown[]>([]);
  brands = signal<AutoDropdown[]>([]);
  attributeDefinitions = signal<AttributeDefinitionDropdown[]>([]);

  private productService = inject(ProductService);
  private destroyRef = inject(DestroyRef);
  private base = inject(BaseApiService);
  private activatedRoute = inject(ActivatedRoute);
  private router = inject(Router);
  private formservice = inject(FormDataService);

  submit = signal<boolean>(false);
  formSubmitted = signal<boolean>(false);
  backendErrors = signal<Record<string, string[]>>({});
  errors = signal<string[]>([]);
  uomList = signal(enumToOptions(UOM, true));
  productTypes = signal(enumToOptions(ProductType, true));
  isEditMode = signal<boolean>(false);
  existingVariantIds = signal<string[]>([]);
  variantImagePreviews = signal<Record<number, string>>({});
  warehouseLocations = signal<Record<number, AutoDropdown[]>>({});
  autoGeneratedSku = signal<Record<number, string>>({});
  /** UI-only: tracks which variant indices are collapsed */
  collapsedVariants = signal<Set<number>>(new Set());

  productModel = signal<ProductDTO>(this.productService.createDefaultProduct());

  ngOnInit() {
    this.loadFormLookups();
    this.activatedRoute.paramMap.pipe(
      takeUntilDestroyed(this.destroyRef)).subscribe(param => {
        const id = param.get('id');
        if (id) {
          this.isEditMode.set(true);
          this.loadProduct(id);
        }
      });
  }

  productForm = form(this.productModel, (schema) => {
    required(schema.productName, { message: 'Product Name is required', });
    required(schema.productNumber, { message: 'Product Number is required' });
    required(schema.uom, { message: 'UOM is required' });
    required(schema.productType, { message: 'Product Type is required' });
    required(schema.productCategoryId, { message: 'Category is required' });

    applyEach(schema.variants, (variant) => {
      required(variant.sku, { message: 'SKU is required', });

      validate(variant.costPrice, ({ value }) => {
        const price = value();
        if (price == null || price <= 0) {
          return { kind: 'positiveCostPrice', message: 'Cost price must be greater than 0' };
        }
        return null;
      });

      validate(variant.sellingPrice, ({ value }) => {
        const price = value();
        if (price == null || price <= 0) {
          return { kind: 'positiveSellingPrice', message: 'Selling price must be greater than 0' };
        }
        return null;
      });

      applyEach(variant.initialStock, (stock) => {
        required(stock.warehouseId, { message: 'Warehouse is required', });
        validate(stock.quantity, ({ value }) => {
          const qty = value();
          if (qty == null || qty <= 0) {
            return { kind: 'positiveQuantity', message: 'Quantity must be greater than 0' };
          }
          return null;
        });

        validate(stock.unitCost, ({ value }) => {
          const cost = value();
          if (cost == null || cost <= 0) {
            return { kind: 'positiveUnitCost', message: 'Unit cost must be greater than 0' };
          }
          return null;
        });

        validate(stock.warehouseId, ({ value, valueOf }) => {
          const currentWarehouseId = value();

          if (!currentWarehouseId) {
            return null;
          }

          const currentLocationId = valueOf(stock.warehouseLocationId);
          const stockRows = valueOf(variant.initialStock) ?? [];
          const currentKey = `${currentWarehouseId}|${currentLocationId ?? ''}`;

          const duplicateCount = stockRows.filter(
            (s) => `${s.warehouseId}|${s.warehouseLocationId ?? ''}` === currentKey
          ).length;

          if (duplicateCount > 1) {
            return {
              kind: 'duplicateWarehouseLocation',
              message: 'This combination is already added to this variant',
            };
          }

          return null;
        });
      });
    });
  });

  updateField<K extends keyof ProductDTO>(field: K, value: ProductDTO[K]) {
    this.productModel.update(prev => this.productService.updateField(prev, field, value));
  }

  updateLineField<K extends keyof ProductVariantDto>(
    index: number,
    field: K,
    value: ProductVariantDto[K]
  ) {
    this.productModel.update(prev => this.productService.updateLineField(prev, index, field, value));
  }
  getAttributeValue(variant: ProductVariantDto, definitionId: number): number | null {
    return variant.attributeValues?.find(a => a.attributeDefinitionId === definitionId)?.attributeValueId ?? null;
  }
  updateVariantAttributeField(variantIndex: number, attributeDefinitionId: number, value: number | null): void {
    this.productModel.update(prev =>
      this.productService.setVariantAttributeValue(prev, variantIndex, attributeDefinitionId, value, this.attributeDefinitions())
    );
    this.maybeAutoGenerateSku(variantIndex);
  }

  updateVariantStockField<K extends keyof WareHouseStockDto>(
    variantIndex: number,
    stockIndex: number,
    field: K,
    value: WareHouseStockDto[K]
  ) {
    this.productModel.update(prev =>
      this.productService.updateVariantStockField(prev, variantIndex, stockIndex, field, value)
    );
  }

  addVariant(): void {
    this.productModel.update(prev => ({
      ...prev,
      variants: [...prev.variants, this.productService.createNewVariant(prev.variants)]
    }));
  }

  deleteVariant(variantIndex: number): void {
    const targetVariant = this.productModel().variants[variantIndex];
    const error = this.productService.canDeleteVariant(
      this.isEditMode(),
      targetVariant,
      this.existingVariantIds()
    );

    if (error) {
      this.errors.set([error]);
      return;
    }

    this.errors.set([]);
    this.productModel.update(prev => this.productService.deleteVariant(prev, variantIndex));

    // Re-index collapsed set: remove deleted index, shift higher indices down by 1
    this.collapsedVariants.update(prev => {
      const next = new Set<number>();
      prev.forEach(idx => {
        if (idx < variantIndex) next.add(idx);
        else if (idx > variantIndex) next.add(idx - 1);
      });
      return next;
    });
  }

  /** Toggle collapse/expand for a single variant card (UI state only) */
  toggleVariant(idx: number): void {
    this.collapsedVariants.update(prev => {
      const next = new Set(prev);
      if (next.has(idx)) next.delete(idx);
      else next.add(idx);
      return next;
    });
  }

  addStockLine(variantIndex: number): void {
    const stockArray = this.productModel().variants[variantIndex].initialStock;

    if (stockArray.length === 0) {
      this.productModel.update(prev => this.productService.addFirstStockLine(prev, variantIndex));
      return;
    }

    const lastIndex = stockArray.length - 1;
    const currentStockRow = this.productForm.variants[variantIndex].initialStock[lastIndex];
    const isInvalid = currentStockRow.warehouseId().invalid()
      || currentStockRow.quantity().invalid()
      || currentStockRow.unitCost().invalid();

    if (isInvalid) {
      currentStockRow.warehouseId().markAsTouched();
      currentStockRow.quantity().markAsTouched();
      currentStockRow.unitCost().markAsTouched();
      return;
    }

    this.productModel.update(prev => this.productService.addStockLine(prev, variantIndex));
  }

  deleteStockLine(variantIndex: number, stockIndex: number): void {
    const targetVariant = this.productModel().variants[variantIndex];
    const error = this.productService.canModifyInitialStock(
      this.isEditMode(),
      targetVariant,
      this.existingVariantIds()
    );

    if (error) {
      this.errors.set([error]);
      return;
    }

    this.errors.set([]);
    this.productModel.update(prev => this.productService.deleteStockLine(prev, variantIndex, stockIndex));
  }

  createProduct(event: Event) {
    if (this.submit()) {
      return;
    }

    if (this.duplicateVariantIndices().size > 0) {
      this.errors.set(['Two or more variants have the same attribute combination. Each variant must be unique.']);
      return;
    }

    event.preventDefault();
    this.submit.set(true);
    this.formSubmitted.set(true);

    if (this.productForm().invalid()) {
      this.productForm().markAsTouched();
      this.submit.set(false);
      return;
    }

    this.errors.set([]);
    this.backendErrors.set({});
    const formvalue = this.productForm().value() as ProductDTO;

    //Filters empty Attributes
    const payload: ProductDTO = {
      ...formvalue,
      variants: formvalue.variants.map(variant => ({
        ...variant,
        attributeValues: (variant.attributeValues ?? [])
          .filter(attribute =>
            attribute.attributeDefinitionId != null &&
            attribute.attributeValueId != null
          )
      }))
    };

    this.productService.saveProduct(payload, this.isEditMode())
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          if (this.isEditMode()) {
            this.router.navigate(['Inventory', 'productlist']);
            this.base.globalMessage('success', 'Product Updated Successfully', false);
            return;
          }

          this.base.globalMessage('success', 'Product Added Successfully', false);
          this.productForm().reset({
            ...this.productService.createDefaultProduct(),
            variants: [{ ...this.productService.createDefaultVariant() }]
          });
          //Remove Images
          this.variantImagePreviews.set({});

          this.submit.set(false);
          this.formSubmitted.set(false);
        },
        error: (err) => {
          if (err.error.errors) {
            this.backendErrors.set(err.error.errors);
          } else {
            this.base.handleError(err, err.error.message);
          }
          this.submit.set(false);
        }
      });
  }

  loadFormLookups(): void {
    this.productService.getFormLookups()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (res) => {
          this.wareHouses.set(res.warehouses);
          this.productCategories.set(res.categories);
          this.brands.set(res.brands);
          this.attributeDefinitions.set(res.attributeDefinitions);
        },
        error: (err) => {
          this.base.handleError(err, err.error?.message);
        }
      });
  }

  loadProduct(id: string) {
    this.productService.getProductById(id)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (data) => {
          this.productModel.set(data);
          const previews: Record<number, string> = {};

          data.variants.forEach((variant, index) => {
            if (variant.imageUrl) {
              previews[index] = variant.imageUrl;
            }
          });

          this.variantImagePreviews.set(previews);
          this.existingVariantIds.set(this.productService.extractExistingVariantIds(data));
        },
        error: (err) => {
          this.base.handleError(err, err.error?.message);
          this.router.navigate(['Inventory', 'productlist']);
        }
      });
  }

  onWarehouseChange(variantIndex: number, stockIndex: number, warehouseId: number | null): void {
    this.updateVariantStockField(variantIndex, stockIndex, 'warehouseId', warehouseId);
    this.updateVariantStockField(variantIndex, stockIndex, 'warehouseLocationId', null);

    if (warehouseId == null || this.warehouseLocations()[warehouseId]) {
      return;
    }

    this.loadWarehouseLocations(warehouseId);
  }

  loadWarehouseLocations(warehouseId: number): void {
    this.productService.getLocationsByWarehouse(warehouseId)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (locations) => {
          this.warehouseLocations.update(current => ({ ...current, [warehouseId]: locations }));
        },
        error: (err) => {
          this.base.handleError(err, err.error?.message);
        }
      });
  }

  getWarehouseLocations(warehouseId: number | null): AutoDropdown[] {
    if (warehouseId == null) {
      return [];
    }

    return this.warehouseLocations()[warehouseId] ?? [];
  }

  onVariantImageSelected(event: Event, variantIndex: number) {
    const preview = signal(this.variantImagePreviews()[variantIndex] ?? '');
    const file = this.formservice.onImageSelected(event, preview);

    if (!file) {
      return;
    }

    const previewUrl = URL.createObjectURL(file);
    this.variantImagePreviews.update(prev => ({ ...prev, [variantIndex]: previewUrl }));
    this.productModel.update(prev => this.productService.setVariantImage(prev, variantIndex, file));
  }

  removeVariantImage(variantIndex: number) {
    const preview = signal(this.variantImagePreviews()[variantIndex] ?? '');
    this.formservice.removeImage(preview, `variantImage_${variantIndex}`);
    this.variantImagePreviews.update(prev => ({ ...prev, [variantIndex]: '' }));
    this.productModel.update(prev =>
      this.productService.removeVariantImage(prev, variantIndex, this.isEditMode())
    );
  }

  duplicateVariantIndices = computed<Set<number>>(() =>
    this.productService.findDuplicateVariantIndices(
      this.productModel().variants ?? [],
      this.attributeDefinitions() ?? []
    )
  );

  generateSku(variantIndex: number): void {
    const newSku = this.productService.buildSkuFromAttributes(
      this.productModel(),
      variantIndex,
      this.attributeDefinitions()
    );
    this.autoGeneratedSku.update(prev => ({ ...prev, [variantIndex]: newSku }));
    this.updateLineField(variantIndex, 'sku', newSku);
  }

  private maybeAutoGenerateSku(variantIndex: number): void {
    const variant = this.productModel().variants[variantIndex];

    if (!this.productService.shouldAutoGenerateSku(
      variant,
      this.isEditMode(),
      this.existingVariantIds(),
      this.autoGeneratedSku()[variantIndex]
    )) {
      return;
    }

    this.generateSku(variantIndex);
  }
  //Locked Stock add and delete on edit
  lockedVariantIndices = computed<Set<number>>(() => {
    if (!this.isEditMode()) return new Set<number>();
    const existingIds = this.existingVariantIds();
    const locked = new Set<number>();
    this.productModel().variants.forEach((v, idx) => {
      if (v.id && existingIds.includes(v.id)) locked.add(idx);
    });
    return locked;
  });
}
